### PR TITLE
add maildev as a new service

### PR DESCRIPTION
**Pull request by heyitsmaimai**

### CODE REVIEW

**Comment by heyitsmaimai** [comment]
@Wardormeur add it as a dependency in the environments?

**Comment by Wardormeur** [comment]
Nope, as a dependency to the service zen in docker-compose ;)
https://docs.docker.com/compose/compose-file/#depends_on

**Comment by heyitsmaimai** [comment]
@Wardormeur uhh i think i did?

**Comment by Wardormeur** [comment]
My bad. I'm blind. You indeed did :)
I would recommend not using the port 80, 1080 is fine by itself

**Comment by heyitsmaimai** [comment]
@Wardormeur if i only have 1080 and not 1080:80 then the maildev UI is not accessible on 1080

**Comment by Wardormeur** [comment]
It's a mapping, it should be 1080:1080 :)

**Pull request merged**
