### PR TITLE
added cp-docker-development link to README.md

### PR DESCRIPTION
**Pull request by niccokunzmann**
I added a link to the current automation of the installation. It points to my repository. This may help getting started with the platform more easily.

### CODE REVIEW

**Comment by tangentfairy** [comment]
@niccokunzmann at the moment @adhorrig is reviewing and testing your development setup, we'll be in touch with any updates

**Comment by tangentfairy** [comment]
Hi @niccokunzmann - we had a few issues with the native ubuntu script:

- There is no password set for the default postgres user and that seems to cause problems when setting up the database.
- The postgres commands do not seem to work if the path is not set on the users computer
- We needed to do an npm install -d for some reason to install all the modules correctly
- The script does not fork the other code repositories: cp-zen-platform, cp-salesforce-service etc. It does ask you to fork the cp-local-development, but I think we need to mention that you need all services forked to be set up.

I think if we fix the above issues we might be able to add it.

We still need someone to test the docker setup - it would be preferred if a community member would be able to try the setup.

**Comment by niccokunzmann** [comment]
I will have a look at the issues 1,2,3, too. 

issue 4: The script does not clone anything because this is done by the command that can be issued after the script: `./localdev.js init zen`. I think, a good solution would be to tell the user which part of the installation was done by the script and at the end the script suggests which commands were to be run when the script finished.

**Comment by tangentfairy** [comment]
Cool, it would be good to have a call with you sometime soon to discuss the system in general, and what type of things you'd like to work on!

**Comment by niccokunzmann** [comment]
@tangentfairy there were two students at google code-in yesterday, who did the task to set up the environment and it worked with the Ubuntu script. Also, I ran it now and it worked, too. Work means

- all repositories are cloned
- zen is served at localhost:8000

I think that it works under a fresh Ubuntu. I am not able to test any other Ubuntus as I do not possess them. I can not reproduce your issues. We should talk about them and fix them to make the script more robust. But, I would like your help on that.

**Comment by tangentfairy** [comment]
We have added the docker setup here now: https://github.com/CoderDojo/cp-local-development/commit/9bf36c333d813db5a6967eeab93b9f88e7c76514 which I think can be the defacto way of setting up if there is an issue with native setup. We tested this at our last hackathon and it worked well.

**Pull request closed without merging**
